### ISSUE TITLE
cloud client mod with optifine makes the settings a whole mess with weird bugs like dynamic fov set on default and u cant turn it back off

### ISSUE THREAD

**Issue by Minecraft117iscool** [CloudClientDev/cloudclient#1]

**Comment by PuedoYT** [comment]
Cloud Client does not support Optifine as an extra mod at the moment. So it is normal that you are having issues with Optifine and Cloud Client installed at the same time.

**Comment by jordoncodes** [comment]
I believe this is fixed

**Comment by duplidev** [comment]
Has been fixed
