### ISSUE TITLE
Some hud settings reset to default after game restart

### ISSUE THREAD

**Issue by Stardust-kyun** [CloudClientDev/cloudclient#10]
After restarting the game, I've noticed the following behaviors:
- Hud elements reset their background to the default "enabled" state, even if they were previously disabled.
- The client's color scheme resets to the default light mode, even if it was previously in dark mode.
Cloud Client is the only mod enabled when this issue to occurs, and the version is 1.8.9.

**Comment by duplidev** [comment]
Which version of the client are you using? This should be fixed in v1.3.3

**Comment by Stardust-kyun** [comment]
Issue created on version 1.3.2, fixed in 1.3.3.
