### ISSUE TITLE
if you pick a certain font it will crash the game, and then it will keep crashing on startup

### ISSUE THREAD

**Issue by LastLaffs** [CloudClientDev/cloudclient#12]
![image](https://user-images.githubusercontent.com/102743584/211132829-38619574-d3b5-4d7b-b73a-e2c0757278eb.png)

**Comment by duplidev** [comment]
Some fonts are not compatible.
The client saves the font which is not working and tries to load it on startup. Try deleting the config located in Appdata or user home /.cloud/cloudconfig.json

**Comment by LastLaffs** [comment]
> Some fonts are not compatible. The client saves the font which is not working and tries to load it on startup. Try deleting the config located in Appdata or user home /.cloud/cloudconfig.json

Ok thanks i already knew that the client was saving the font i just didnt know where the config was. Tysm

**Comment by LastLaffs** [comment]
The font that was crashing the game was MS Gothic, for your help :)
