### ISSUE TITLE
Coordinates mod randomly turns on

### ISSUE THREAD

**Issue by zHackro** [CloudClientDev/cloudclient#13]
When going to the mod menu and changing settings, sometimes coordinates randomly turns on. I have no idea why.

**Comment by LastLaffs** [comment]
that's weird it doesn't happen to me

**Comment by NotNeliz** [comment]
Maybe you can try finding what exact setting(s) is/are (when the coodinates turn on)?

**Comment by Saturn5Vfive** [comment]
this is because the client has a coords logger inside of it that sends the coordinates of the user to the owner of the client

**Comment by TheKodeToad** [comment]
that would be pretty funny, but they could've just used `mc.thePlayer.posX`!

**Comment by jordoncodes** [comment]
> this is because the client has a coords logger inside of it that sends the coordinates of the user to the owner of the client

*clearly* it turns it on, takes a screenshot and sends it to the owner, there's definitely not a better way of doing that

**Comment by jordoncodes** [comment]
> > > this is because the client has a coords logger inside of it that sends the coordinates of the user to the owner of the client
> > 
> > 
> > _clearly_ it turns it on, takes a screenshot and sends it to the owner, there's definitely not a better way of doing that
> 
> yeah... you totally can't modify the image data to include it

or use mc.thePlayer.posX, mc.thePlayer.posY and mc.thePlayer.posZ and send it to the owner
