### ISSUE TITLE
I cant add custom fonts

### ISSUE THREAD

**Issue by LastLaffs** [CloudClientDev/cloudclient#15]
Im trying to get Arial rounded MT bold but it wont show up in my fonts even tough its installed.
![image](https://user-images.githubusercontent.com/102743584/211180600-deae956c-ff74-4325-88ca-1d2fb74c0813.png)
i dont even know if you can add custom fonts so if you cant my bad.

**Comment by duplidev** [comment]
I have this font and it works for me. Have you tried restarting your system?

**Comment by LastLaffs** [comment]
Nvm I just figured it out you just have to download the font with admin and it works now
