### ISSUE TITLE
Third Player Nametag Mod

### ISSUE THREAD

**Issue by Gadet-0** [CloudClientDev/cloudclient#16]

**Comment by DaDevGuy** [comment]
Don't you think you should suggest this on their Discord server?

**Comment by Gadet-0** [comment]
> Don't you think you should suggest this on their Discord server?

can i get the link to their discord?

**Comment by NotNeliz** [comment]
Here you go https://dsc.gg/cloudclientmc :)

**Comment by TheKodeToad** [comment]
As a developer, I find GitHub more convienient for suggestions. Can't speak for the dev(s) here, though, and some prefer the issue tracker specifically for actual issues.

**Comment by DaDevGuy** [comment]
Then you should label it as a suggestion. For the ease of people like us who are looking for actual issues

**Comment by TheKodeToad** [comment]
Collaborators to the repository can add an enchancement and bug tag (regular users can't though :(). They can also automatically be added with templates.

**Comment by duplidev** [comment]
Added Nametag Mod
