### ISSUE TITLE
toggle sprint bug

### ISSUE THREAD

**Issue by ChobojaX** [CloudClientDev/cloudclient#2]
Tested on linux, 1.8.9

In Vanilla sprint mode, After I enable Auto sprint mode and disable I go forward, auto sprint is turned on. To stop auto sprint after disable by keybind, I have to press vanilla sprint key one time.

VIdeo: (Vanilla sprint keybind is Semicolon, Toggle sprint keybind is F)
https://youtu.be/YDCAaxNBCwU

**Comment by duplidev** [comment]
Thanks for the report, has been fixed in the next update.
