### ISSUE TITLE
Smooth scrolling in mods GUI

### ISSUE THREAD

**Issue by jordoncodes** [CloudClientDev/cloudclient#20]
Could there be an option for smooth scrolling in the mods gui (and maybe the ability to adjust the scroll speed, it scrolls slowly for me)

**Comment by LastLaffs** [comment]
recommend this in their [discord](https://dsc.gg/cloudclientmc)

**Comment by jordoncodes** [comment]
> recommend this in their [discord](https://dsc.gg/cloudclientmc) 

Okay, made a suggestion.
