### ISSUE TITLE
NanoVG Rendering

### ISSUE THREAD

**Issue by TheKodeToad** [cloudclientdev/cloudclient#21]
This would defintely simplify font and rounded rectangle rendering.

See:
https://github.com/memononen/nanovg
https://github.com/DJtheRedstoner/LWJGLTwoPointFive

I made a thing to avoid wrestling with Gradle :)
https://github.com/Sol-Client/LWJGL-Patched

**Comment by CodeKid0** [comment]
Great suggestion, however may be a little hard to implement and I think for the rounded rectangles GLSL Shaders can be used.

**Comment by TheKodeToad** [comment]
It's not very hard to implement. It didn't take me long.
