### ISSUE TITLE
Motion blur getting disabled by fire

### ISSUE THREAD

**Issue by Nitrohell** [cloudclientdev/cloudclient#24]
When player is burning, motion blur gets disabled, and gets enabled after it's not burning anymore
https://streamable.com/2k39ki

**Comment by jordoncodes** [comment]
what mods do you have?

**Comment by Nitrohell** [comment]
![image](https://user-images.githubusercontent.com/83920976/212780174-bdbc95db-bf5c-4c23-93be-8f606eaca7a4.png)

**Comment by jordoncodes** [comment]
sorry I havent replied but try it with just cloud or just cloud + optifine to see if it's another mod (or optifine)
