### ISSUE TITLE
Feature Request: I18n Support

### ISSUE THREAD

**Issue by jiesou** [CloudClientDev/cloudclient#33]
I wish CloudClient would take non-native speakers of English into account, add **multilingual** support (e.g. Chinese).

There is another feature that I particularly like: chat translation. Similar to [Real Time Chat Translation Mod](https://github.com/ringosham/TranslateMod)
Most of the Minecraft Clients I know don't have this feature, it would be cool if the Cloud Client had it!

**Comment by NotNeliz** [comment]
Hey,
you can send a request to add mods/features in the discord server https://dsc.gg/cloudclientmc
Hope this helps!
