### ISSUE TITLE
HUD mods not loading

### ISSUE THREAD

**Issue by NotNeliz** [CloudClientDev/cloudclient#43]
As the title explains HUD mods are not loading like: keystrokes, block info, armour status etc.

Tested on Mac (6-2-2023)
Version: v1.3.4 (1.8.9)

**Comment by NerdHaxx** [comment]
probably something to do with your operating system (mac). maybe try using the client in a Windows or Linux machine and see if the above error occurs?

**Comment by NotNeliz** [comment]
Worked again after reinstalling forge, probably messed up with older files
