### ISSUE TITLE
mods not showing up

### ISSUE THREAD

**Issue by TrueHerobrine** [cloudclientdev/cloudclient#45]
Mods simply don't show up for me. Using FPS, ping and keystrokes and I don't see a single one on my screen.
![2023-02-18_12 54 22](https://user-images.githubusercontent.com/69488295/219880962-0622a58a-a60b-4ba2-a45d-e658fa2f4379.png)
(Yes, that screenshot is Cloud Client)
![2023-02-18_12 55 27](https://user-images.githubusercontent.com/69488295/219881015-b0cd15a5-b93a-46bd-ad21-b75eb66fc5fb.png)

**Comment by duplidev** [comment]
Either try changing your GUI scale or delete the config in appdata/.cloud/cloudconfig.json

**Comment by NerdHaxx** [comment]
are you using a mod that messes around with the rendering engine along side cloud? I mean mods with names such as 'fps booster' or smth like that?
