### ISSUE TITLE
Block Status Texture

### ISSUE THREAD

**Issue by NotNeliz** [CloudClientDev/cloudclient#7]
Not really important but some textures/texts are messed up on the Block Status mod
(tested on windows)

![bug2](https://user-images.githubusercontent.com/121827762/210275469-63b5e00e-c80b-410b-8630-bc03206a4372.png)
![bug3](https://user-images.githubusercontent.com/121827762/210276025-8e4c710a-e8fc-400e-8781-600461a236d9.png)
![bug4](https://user-images.githubusercontent.com/121827762/210276028-44228983-1dd6-4b6e-8904-3e3d15d57cc4.png)
![b](https://user-images.githubusercontent.com/121827762/210276035-4106c88e-dc3f-42d0-8e24-8198ab0cb327.png)
![bug7](https://user-images.githubusercontent.com/121827762/210276043-39110570-826d-4567-bc93-09943a3cb992.png)
![bug8](https://user-images.githubusercontent.com/121827762/210276048-df0a9ba1-61a2-45c3-bdf4-e4b1ec80f10e.png)

**Comment by NotNeliz** [comment]
I will check other blocks

**Comment by NotNeliz** [comment]
Some other messed up textures/texts

![bug4](https://user-images.githubusercontent.com/121827762/210275738-7972ff30-6992-4bb1-8626-177e8aaf28c1.png)
![bug4](https://user-images.githubusercontent.com/121827762/210275751-6c1b081e-ef3c-4d5a-8b60-84f600c9f67e.png)
![bug8](https://user-images.githubusercontent.com/121827762/210275772-5bc8d28d-7376-43b8-bd9e-6fc9ff14c192.png)

**Comment by jordoncodes** [comment]
I might make a pr fixing this
